galasa-dev/eclipse

- galasa-eclipse-parent/dev.galasa.eclipse.feature/feature.xml
- galasa-eclipse-parent/dev.galasa.eclipse.feature/pom.xml
- galasa-eclipse-parent/dev.galasa.eclipse.site/category.xml
- galasa-eclipse-parent/dev.galasa.eclipse.site/pom.xml
- galasa-eclipse-parent/dev.galasa.eclipse/META-INF/MANIFEST.MF
- galasa-eclipse-parent/dev.galasa.eclipse/pom.xml
- galasa-eclipse-parent/dev.galasa.simbank.feature/feature.xml
- galasa-eclipse-parent/dev.galasa.simbank.feature/pom.xml
- galasa-eclipse-parent/dev.galasa.simbank.ui/META-INF/MANIFEST.MF
- galasa-eclipse-parent/dev.galasa.simbank.ui/pom.xml
- galasa-eclipse-parent/dev.galasa.zos.feature/feature.xml
- galasa-eclipse-parent/dev.galasa.zos.feature/pom.xml
- galasa-eclipse-parent/dev.galasa.zos3270.ui/META-INF/MANIFEST.MF
- galasa-eclipse-parent/dev.galasa.zos3270.ui/pom.xml
- galasa-eclipse-parent/pom.xml
> Bump all eclipse plugins to 17

- galasa-eclipse-parent/dev.galasa.eclipse/src/dev/galasa/eclipse/ui/run/storedartifacts/ArtifactEditor.java
- tekton/pipe-eclipse-repo-build.yaml
- tekton/prun-main-eclipse-build.yaml
- tekton/res-git-eclipse-main.yaml
- tekton/res-git-eclipse-staging.yaml
- tekton/task-eclipse-repo-build.yaml
> Allow Find in storedartifact text editor

- galasa-eclipse-parent/dev.galasa.eclipse/src/dev/galasa/eclipse/ui/wizards/submittests/SelectTestsWizardPage.java
> Sort test selection

- galasa-eclipse-parent/dev.galasa.eclipse/src/dev/galasa/eclipse/ui/runs/Run.java
> add additional data to the run view

- galasa-eclipse-parent/dev.galasa.eclipse/plugin.xml
- galasa-eclipse-parent/dev.galasa.eclipse/src/dev/galasa/eclipse/ui/runs/DeleteRunAction.java
- galasa-eclipse-parent/dev.galasa.eclipse/src/dev/galasa/eclipse/ui/runs/DeleteRunJob.java
- galasa-eclipse-parent/dev.galasa.eclipse/src/dev/galasa/eclipse/ui/runs/ResetRunAction.java
- galasa-eclipse-parent/dev.galasa.eclipse/src/dev/galasa/eclipse/ui/runs/ResetRunJob.java
> Add delete and reset actions to the runs view

- galasa-eclipse-parent/dev.galasa.eclipse/pom.xml
> boot to 17

- galasa-eclipse-parent/dev.galasa.eclipse.feature/feature.xml
- galasa-eclipse-parent/dev.galasa.eclipse.feature/pom.xml
- galasa-eclipse-parent/dev.galasa.eclipse.site/category.xml
- galasa-eclipse-parent/dev.galasa.eclipse.site/pom.xml
- galasa-eclipse-parent/dev.galasa.eclipse/META-INF/MANIFEST.MF
- galasa-eclipse-parent/dev.galasa.eclipse/pom.xml
- galasa-eclipse-parent/dev.galasa.simbank.feature/feature.xml
- galasa-eclipse-parent/dev.galasa.simbank.feature/pom.xml
- galasa-eclipse-parent/dev.galasa.simbank.ui/META-INF/MANIFEST.MF
- galasa-eclipse-parent/dev.galasa.simbank.ui/pom.xml
- galasa-eclipse-parent/dev.galasa.zos.feature/feature.xml
- galasa-eclipse-parent/dev.galasa.zos.feature/pom.xml
- galasa-eclipse-parent/dev.galasa.zos3270.ui/META-INF/MANIFEST.MF
- galasa-eclipse-parent/dev.galasa.zos3270.ui/pom.xml
- galasa-eclipse-parent/pom.xml
> Bump to 18

- galasa-eclipse-parent/dev.galasa.eclipse/plugin.xml
> restore eclipse prolog

- galasa-eclipse-parent/dev.galasa.eclipse.feature/feature.xml
- galasa-eclipse-parent/dev.galasa.eclipse.feature/pom.xml
- galasa-eclipse-parent/dev.galasa.eclipse/pom.xml
> correct versions

- galasa-eclipse-parent/dev.galasa.eclipse.feature/feature.xml
- galasa-eclipse-parent/dev.galasa.eclipse.feature/pom.xml
- galasa-eclipse-parent/dev.galasa.eclipse.site/category.xml
- galasa-eclipse-parent/dev.galasa.eclipse.site/pom.xml
- galasa-eclipse-parent/dev.galasa.eclipse/META-INF/MANIFEST.MF
- galasa-eclipse-parent/dev.galasa.eclipse/pom.xml
- galasa-eclipse-parent/dev.galasa.simbank.feature/feature.xml
- galasa-eclipse-parent/dev.galasa.simbank.feature/pom.xml
- galasa-eclipse-parent/dev.galasa.simbank.ui/META-INF/MANIFEST.MF
- galasa-eclipse-parent/dev.galasa.simbank.ui/pom.xml
- galasa-eclipse-parent/dev.galasa.zos.feature/feature.xml
- galasa-eclipse-parent/dev.galasa.zos.feature/pom.xml
- galasa-eclipse-parent/dev.galasa.zos3270.ui/META-INF/MANIFEST.MF
- galasa-eclipse-parent/dev.galasa.zos3270.ui/pom.xml
- galasa-eclipse-parent/pom.xml
> Bump to 0.19.0

- galasa-eclipse-parent/dev.galasa.eclipse/pom.xml
> add latest boot to eclipse

- galasa-eclipse-parent/dev.galasa.simbank.ui/pom.xml
Signed-off-by: Will Yates <hobbit1983@gmail.com>
> bump simbank tests to 0.16.0

- galasa-eclipse-parent/dev.galasa.eclipse.site/httpd.conf
- tekton/pipe-eclipse-repo-build.yaml
- tekton/prun-main-eclipse-build.yaml
- tekton/task-eclipse-repo-build.yaml
> corrections for new k8s

- galasa-eclipse-parent/dev.galasa.eclipse.feature/feature.xml
- galasa-eclipse-parent/dev.galasa.eclipse.feature/pom.xml
- galasa-eclipse-parent/dev.galasa.eclipse.site/category.xml
- galasa-eclipse-parent/dev.galasa.eclipse.site/pom.xml
- galasa-eclipse-parent/dev.galasa.eclipse/META-INF/MANIFEST.MF
- galasa-eclipse-parent/dev.galasa.eclipse/pom.xml
- galasa-eclipse-parent/dev.galasa.simbank.feature/feature.xml
- galasa-eclipse-parent/dev.galasa.simbank.feature/pom.xml
- galasa-eclipse-parent/dev.galasa.simbank.ui/META-INF/MANIFEST.MF
- galasa-eclipse-parent/dev.galasa.simbank.ui/pom.xml
- galasa-eclipse-parent/dev.galasa.zos.feature/feature.xml
- galasa-eclipse-parent/dev.galasa.zos.feature/pom.xml
- galasa-eclipse-parent/dev.galasa.zos3270.ui/META-INF/MANIFEST.MF
- galasa-eclipse-parent/dev.galasa.zos3270.ui/pom.xml
- galasa-eclipse-parent/pom.xml
> bump to 20

- galasa-eclipse-parent/dev.galasa.eclipse/src/dev/galasa/eclipse/ui/wizards/submittests/ConfigurationWizardPage.java
- galasa-eclipse-parent/dev.galasa.eclipse/src/dev/galasa/eclipse/ui/wizards/submittests/SelectTestsWizardPage.java
Signed-off-by: James Davies <jdavies47@hotmail.co.uk>
> Changed variable name from master to main

- galasa-eclipse-parent/dev.galasa.eclipse.feature/feature.xml
- galasa-eclipse-parent/dev.galasa.eclipse.feature/pom.xml
- galasa-eclipse-parent/dev.galasa.eclipse.site/category.xml
- galasa-eclipse-parent/dev.galasa.eclipse.site/pom.xml
- galasa-eclipse-parent/dev.galasa.eclipse/META-INF/MANIFEST.MF
- galasa-eclipse-parent/dev.galasa.eclipse/pom.xml
- galasa-eclipse-parent/dev.galasa.simbank.feature/feature.xml
- galasa-eclipse-parent/dev.galasa.simbank.feature/pom.xml
- galasa-eclipse-parent/dev.galasa.simbank.ui/META-INF/MANIFEST.MF
- galasa-eclipse-parent/dev.galasa.simbank.ui/pom.xml
- galasa-eclipse-parent/dev.galasa.zos.feature/feature.xml
- galasa-eclipse-parent/dev.galasa.zos.feature/pom.xml
- galasa-eclipse-parent/dev.galasa.zos3270.ui/META-INF/MANIFEST.MF
- galasa-eclipse-parent/dev.galasa.zos3270.ui/pom.xml
- galasa-eclipse-parent/pom.xml
> Bump to 0.21.0

- galasa-eclipse-parent/dev.galasa.eclipse.feature/feature.xml
- galasa-eclipse-parent/dev.galasa.eclipse.feature/pom.xml
- galasa-eclipse-parent/dev.galasa.eclipse/pom.xml
- galasa-eclipse-parent/dev.galasa.zos3270.ui/pom.xml
> bump distro bundles to 21 for security vulnerability updates

- galasa-eclipse-parent/dev.galasa.eclipse/pom.xml
> bump boot to 23

- galasa-eclipse-parent/dev.galasa.eclipse.feature/feature.xml
- galasa-eclipse-parent/dev.galasa.eclipse.feature/pom.xml
- galasa-eclipse-parent/dev.galasa.eclipse.site/category.xml
- galasa-eclipse-parent/dev.galasa.eclipse.site/pom.xml
- galasa-eclipse-parent/dev.galasa.eclipse/META-INF/MANIFEST.MF
- galasa-eclipse-parent/dev.galasa.eclipse/pom.xml
- galasa-eclipse-parent/dev.galasa.simbank.feature/feature.xml
- galasa-eclipse-parent/dev.galasa.simbank.feature/pom.xml
- galasa-eclipse-parent/dev.galasa.simbank.ui/META-INF/MANIFEST.MF
- galasa-eclipse-parent/dev.galasa.simbank.ui/pom.xml
- galasa-eclipse-parent/dev.galasa.zos.feature/feature.xml
- galasa-eclipse-parent/dev.galasa.zos.feature/pom.xml
- galasa-eclipse-parent/dev.galasa.zos3270.ui/META-INF/MANIFEST.MF
- galasa-eclipse-parent/dev.galasa.zos3270.ui/pom.xml
- galasa-eclipse-parent/pom.xml
> Bump to 24

- galasa-eclipse-parent/dev.galasa.zos3270.ui/src/dev/galasa/zos3270/ui/terminal/TerminalView.java
> Workaround for defect in Eclipse SWT

- galasa-eclipse-parent/dev.galasa.eclipse/pom.xml
> bump boot to 24 for java 11

- galasa-eclipse-parent/dev.galasa.eclipse.feature/feature.xml
- galasa-eclipse-parent/dev.galasa.eclipse.feature/pom.xml
- galasa-eclipse-parent/dev.galasa.eclipse.site/category.xml
- galasa-eclipse-parent/dev.galasa.eclipse.site/pom.xml
- galasa-eclipse-parent/dev.galasa.eclipse/META-INF/MANIFEST.MF
- galasa-eclipse-parent/dev.galasa.eclipse/pom.xml
- galasa-eclipse-parent/dev.galasa.simbank.feature/feature.xml
- galasa-eclipse-parent/dev.galasa.simbank.feature/pom.xml
- galasa-eclipse-parent/dev.galasa.simbank.ui/META-INF/MANIFEST.MF
- galasa-eclipse-parent/dev.galasa.simbank.ui/pom.xml
- galasa-eclipse-parent/dev.galasa.zos.feature/feature.xml
- galasa-eclipse-parent/dev.galasa.zos.feature/pom.xml
- galasa-eclipse-parent/dev.galasa.zos3270.ui/META-INF/MANIFEST.MF
- galasa-eclipse-parent/dev.galasa.zos3270.ui/pom.xml
- galasa-eclipse-parent/pom.xml
> Bump 0.25.0

- galasa-eclipse-parent/dev.galasa.simbank.ui/pom.xml
Signed-off-by: James Davies <jdavies47@hotmail.co.uk>
> bumpd simbank version

- galasa-eclipse-parent/dev.galasa.zos.feature/feature.xml
- galasa-eclipse-parent/dev.galasa.zos.feature/pom.xml
- galasa-eclipse-parent/dev.galasa.zos3270.ui/META-INF/MANIFEST.MF
- galasa-eclipse-parent/dev.galasa.zos3270.ui/pom.xml
- galasa-eclipse-parent/dev.galasa.zos3270.ui/src/dev/galasa/zos3270/ui/preferences/PreferenceConstants.java
- galasa-eclipse-parent/dev.galasa.zos3270.ui/src/dev/galasa/zos3270/ui/preferences/Zos3270Preferences.java
- galasa-eclipse-parent/dev.galasa.zos3270.ui/src/dev/galasa/zos3270/ui/preferences/Zos3270PreferencesInitialiser.java
- galasa-eclipse-parent/dev.galasa.zos3270.ui/src/dev/galasa/zos3270/ui/terminal/TerminalView.java
> Colour support

- galasa-eclipse-parent/dev.galasa.eclipse.feature/feature.xml
- galasa-eclipse-parent/dev.galasa.eclipse.feature/pom.xml
- galasa-eclipse-parent/dev.galasa.eclipse/pom.xml
Signed-off-by: Aaron Jhaj <Aaron.Jhaj@ibm.com>
> bump commons.lang to 3.12

- galasa-eclipse-parent/dev.galasa.eclipse.feature/feature.xml
- galasa-eclipse-parent/dev.galasa.eclipse.feature/pom.xml
- galasa-eclipse-parent/dev.galasa.eclipse.site/category.xml
- galasa-eclipse-parent/dev.galasa.eclipse.site/pom.xml
- galasa-eclipse-parent/dev.galasa.eclipse/META-INF/MANIFEST.MF
- galasa-eclipse-parent/dev.galasa.eclipse/pom.xml
- galasa-eclipse-parent/dev.galasa.simbank.feature/feature.xml
- galasa-eclipse-parent/dev.galasa.simbank.feature/pom.xml
- galasa-eclipse-parent/dev.galasa.simbank.ui/META-INF/MANIFEST.MF
- galasa-eclipse-parent/dev.galasa.simbank.ui/pom.xml
- galasa-eclipse-parent/dev.galasa.zos.feature/feature.xml
- galasa-eclipse-parent/dev.galasa.zos.feature/pom.xml
- galasa-eclipse-parent/dev.galasa.zos3270.ui/META-INF/MANIFEST.MF
- galasa-eclipse-parent/dev.galasa.zos3270.ui/pom.xml
- galasa-eclipse-parent/pom.xml
Signed-off-by: Jade Carino <jade.carino@ibm.com>
> Bump development to version 0.26.0

- galasa-eclipse-parent/dev.galasa.eclipse/pom.xml
Signed-off-by: Mike Cobbett <77053+techcobweb@users.noreply.github.com>
> eclipse to use boot jar v0.26.0

- galasa-eclipse-parent/dev.galasa.eclipse.feature/feature.xml
- galasa-eclipse-parent/dev.galasa.eclipse.feature/pom.xml
- galasa-eclipse-parent/dev.galasa.eclipse.site/category.xml
- galasa-eclipse-parent/dev.galasa.eclipse.site/pom.xml
- galasa-eclipse-parent/dev.galasa.eclipse/META-INF/MANIFEST.MF
- galasa-eclipse-parent/dev.galasa.eclipse/pom.xml
- galasa-eclipse-parent/dev.galasa.simbank.feature/feature.xml
- galasa-eclipse-parent/dev.galasa.simbank.feature/pom.xml
- galasa-eclipse-parent/dev.galasa.simbank.ui/META-INF/MANIFEST.MF
- galasa-eclipse-parent/dev.galasa.simbank.ui/pom.xml
- galasa-eclipse-parent/dev.galasa.zos.feature/feature.xml
- galasa-eclipse-parent/dev.galasa.zos.feature/pom.xml
- galasa-eclipse-parent/dev.galasa.zos3270.ui/META-INF/MANIFEST.MF
- galasa-eclipse-parent/dev.galasa.zos3270.ui/pom.xml
- galasa-eclipse-parent/pom.xml
Signed-off-by: Eamonn Mansour <47121388+eamansour@users.noreply.github.com>
> Bump eclipse plugin to 0.27.0

- galasa-eclipse-parent/dev.galasa.eclipse.feature/feature.xml
- galasa-eclipse-parent/dev.galasa.eclipse.feature/pom.xml
- galasa-eclipse-parent/dev.galasa.eclipse/pom.xml
- eclipse to use latest framework and boot jar
> mcobbett 1371 bump boot jar ver

- galasa-eclipse-parent/dev.galasa.eclipse.feature/feature.xml
- galasa-eclipse-parent/dev.galasa.eclipse.feature/pom.xml
- galasa-eclipse-parent/dev.galasa.eclipse.site/category.xml
- galasa-eclipse-parent/dev.galasa.eclipse.site/pom.xml
- galasa-eclipse-parent/dev.galasa.eclipse/META-INF/MANIFEST.MF
- galasa-eclipse-parent/dev.galasa.eclipse/pom.xml
- galasa-eclipse-parent/dev.galasa.simbank.feature/feature.xml
- galasa-eclipse-parent/dev.galasa.simbank.feature/pom.xml
- galasa-eclipse-parent/dev.galasa.simbank.ui/META-INF/MANIFEST.MF
- galasa-eclipse-parent/dev.galasa.simbank.ui/pom.xml
- galasa-eclipse-parent/dev.galasa.zos.feature/feature.xml
- galasa-eclipse-parent/dev.galasa.zos.feature/pom.xml
- galasa-eclipse-parent/dev.galasa.zos3270.ui/META-INF/MANIFEST.MF
- galasa-eclipse-parent/dev.galasa.zos3270.ui/pom.xml
- galasa-eclipse-parent/pom.xml
Signed-off-by: Jade Carino <carino_jade@yahoo.co.uk>
> Version bump development to 0.28.0

- galasa-eclipse-parent/dev.galasa.eclipse.feature/feature.xml
- galasa-eclipse-parent/dev.galasa.eclipse.feature/pom.xml
- galasa-eclipse-parent/dev.galasa.eclipse.site/category.xml
- galasa-eclipse-parent/dev.galasa.eclipse.site/pom.xml
- galasa-eclipse-parent/dev.galasa.eclipse/META-INF/MANIFEST.MF
- galasa-eclipse-parent/dev.galasa.eclipse/pom.xml
- galasa-eclipse-parent/dev.galasa.simbank.feature/feature.xml
- galasa-eclipse-parent/dev.galasa.simbank.feature/pom.xml
- galasa-eclipse-parent/dev.galasa.simbank.ui/META-INF/MANIFEST.MF
- galasa-eclipse-parent/dev.galasa.simbank.ui/pom.xml
- galasa-eclipse-parent/dev.galasa.zos.feature/feature.xml
- galasa-eclipse-parent/dev.galasa.zos.feature/pom.xml
- galasa-eclipse-parent/dev.galasa.zos3270.ui/META-INF/MANIFEST.MF
- galasa-eclipse-parent/dev.galasa.zos3270.ui/pom.xml
- galasa-eclipse-parent/pom.xml
Signed-off-by: Mike Cobbett <77053+techcobweb@users.noreply.github.com>
> Bump to version 0.30.0

- galasa-eclipse-parent/dev.galasa.eclipse/pom.xml
- bump up boot jar version dependency
> mcobbett bump version to 30 manually

- galasa-eclipse-parent/dev.galasa.eclipse.feature/feature.xml
- galasa-eclipse-parent/dev.galasa.eclipse.feature/pom.xml
- galasa-eclipse-parent/dev.galasa.eclipse.site/category.xml
- galasa-eclipse-parent/dev.galasa.eclipse.site/pom.xml
- galasa-eclipse-parent/dev.galasa.eclipse/META-INF/MANIFEST.MF
- galasa-eclipse-parent/dev.galasa.eclipse/pom.xml
- galasa-eclipse-parent/dev.galasa.simbank.feature/feature.xml
- galasa-eclipse-parent/dev.galasa.simbank.feature/pom.xml
- galasa-eclipse-parent/dev.galasa.simbank.ui/META-INF/MANIFEST.MF
- galasa-eclipse-parent/dev.galasa.simbank.ui/pom.xml
- galasa-eclipse-parent/dev.galasa.zos.feature/feature.xml
- galasa-eclipse-parent/dev.galasa.zos.feature/pom.xml
- galasa-eclipse-parent/dev.galasa.zos3270.ui/META-INF/MANIFEST.MF
- galasa-eclipse-parent/dev.galasa.zos3270.ui/pom.xml
- galasa-eclipse-parent/pom.xml
Signed-off-by: Jade Carino <carino_jade@yahoo.co.uk>
> Bump development version of Eclipse etc to 0.31.0

- galasa-eclipse-parent/dev.galasa.eclipse.feature/pom.xml
- galasa-eclipse-parent/dev.galasa.eclipse/pom.xml
- galasa-eclipse-parent/dev.galasa.simbank.ui/pom.xml
Related to https://github.com/galasa-dev/projectmanagement/issues/1568
> Bump gson to 2.10.1
